NUMPY BASICS

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)# 1D array
b = np.array([[1,2,3],[4,5,6]])
print(b) # 2D array

c= np.zeros((3,4)) #3x4 array of zeros
print(c)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
d= np.ones((3,3))
print(d)
np.eye(4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
print(np.arange(0,10,2)) # 0 to 10 with step of 2
np.linspace(0,10,5) # 0 to 1 with 5 equally spaced numbers

[0 2 4 6 8]


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

OPERATIONS  

Element wise operations

In [6]:
A= np.array([1,2,3])
B = np.array([4,5,6])
print(A+B) # element-wise addition
print(A-B) # element-wise subtraction
print(A*B) # element-wise multiplication
print(A/B) # element-wise division

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Aggregate Functions

In [7]:
arr = np.array([[1,2,3],[4,5,6]])

arr.sum()         # 21 (all elements)
arr.sum(axis=0)   # [5,7,9] column-wise
arr.sum(axis=1)   # [6,15] row-wise
arr.mean()        # 3.5
arr.min(), arr.max()
arr.std()         # standard deviation
arr.cumsum()      # cumulative sum

array([ 1,  3,  6, 10, 15, 21])

Slicing and Indexing

In [8]:
a = np.array([10, 20, 30, 40, 50])

a[0]       # 10  — first element
a[-1]      # 50  — last element
a[1:4]     # [20 30 40]
print(a[::2])     # [10 20] — every 2nd
a[1:]      # [20 30 40 50]

[10 30 50]


array([20, 30, 40, 50])

2d

In [9]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

m[0, 1]     # 2  — row 0, col 1
m[1, :]     # [4,5,6] — entire row 1
m[:, 2]     # [3,6,9] — entire col 2
m[0:2, 1:3] # [[2,3],[5,6]] — submatrix

array([[2, 3],
       [5, 6]])

In [10]:
a= np.array([1,2,3])
print(a.shape) # (3,) — 1D array with 3 elements
b = np.array([[1,2,3],[4,5,6]])
print(b.flatten()) # [1 2 3 4 5 6] — flatten to 1D
print(a.ravel())
print(b.ravel())

(3,)
[1 2 3 4 5 6]
[1 2 3]
[1 2 3 4 5 6]


In [11]:
x = np.array([1,2,3])
y = np.array([4,5,6])

np.vstack([x, y])    # [[1,2,3],[4,5,6]]
np.hstack([x, y])    # [1,2,3,4,5,6]
print(np.concatenate([x,y]))
print(np.concatenate([x,y],axis=0))
print(np.split(x, 3))       # split into 3 parts

# add/remove dimensions
x[np.newaxis, :]     # (1, 3) — add row dim
x[:, np.newaxis]     # (3, 1) — add col dim

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[array([1]), array([2]), array([3])]


array([[1],
       [2],
       [3]])

STATISTICS

In [12]:
data = np.array([2,4,4,4,5,5,7,9])

np.mean(data)       # 5.0
np.median(data)     # 4.5
print(np.std(data))        # 2.0
np.var(data)        # 4.0
np.percentile(data, 75)  # 5.75
np.corrcoef(data, data)  # correlation matrix

2.0


array([[1., 1.],
       [1., 1.]])

RANDOM

In [13]:
rng = np.random.default_rng(42) # seed for reproducibility

rng.random((3,3))    # 3x3 floats in [0, 1)
rng.integers(0, 10, size=5)  # 5 ints [0,10)
rng.normal(0, 1, 1000)  # normal dist μ=0 σ=1
rng.choice([1,2,3,4], size=3) # random pick
rng.shuffle(arr)      # shuffle in place

# distributions
rng.uniform(0, 10)
rng.binomial(10, 0.5)
rng.poisson(5)

2

lINEAR ALGEBRA

In [14]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# matrix multiplication
A @ B                       # preferred
np.matmul(A, B)              # same as @
np.dot(A, B)                 # dot product

# linalg module
np.linalg.det(A)            # determinant
np.linalg.inv(A)            # inverse
np.linalg.eig(A)            # eigenvalues & vectors
np.linalg.norm(A)           # matrix norm
np.linalg.svd(A)            # singular value decomp
np.linalg.solve(A, [1,2])   # solve Ax = b

array([0. , 0.5])

load a dataset and use it

In [15]:
import pandas as pd 

In [16]:
df = pd.read_csv('Salaries.csv')

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_31048\2827120379.py:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Salaries.csv')


In [17]:
#df.head()
#print(df.dtypes)
df["BasePay"]= pd.to_numeric(df["BasePay"], errors='coerce')

In [18]:
print(df["BasePay"].dtype)
print(np.mean(df["BasePay"]))
print(np.median(df["BasePay"]))
print(np.std(df["BasePay"]))
print(np.percentile(df["BasePay"], 50))

float64
66325.4488404877
nan
42764.491063809946
nan


In [19]:
from scipy import stats

In [20]:
data = [2,4,4,4,5,5,7,9,10,12]
result = stats.describe(data)

In [21]:
result.nobs      # 10  — count
result.mean      # 6.2
result.variance  # 9.51
result.skewness  # 0.63 (right skew)
result.kurtosis  # -0.39
result.minmax    # (2, 12)

(np.int64(2), np.int64(12))

In [22]:
stats.mode(data)          # most frequent value
stats.gmean(data)         # geometric mean
stats.hmean(data)         # harmonic mean
stats.sem(data)           # standard error of mean
stats.iqr(data)           # interquartile range
stats.zscore(data)        # z-score each element
stats.percentileofscore(data, 5)  # 50.0%

np.float64(55.0)

In [23]:
from scipy import stats
data = [78, 82, 85, 90, 88, 76, 95, 84, 79, 91]
t_stat, p_val = stats.ttest_1samp(data, popmean=80)
# t = 2.4495,  p = 0.0736

In [24]:

from scipy import stats
x = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
y = [12, 22, 28, 45, 48, 65, 68, 82, 88, 98]
r, p_val = stats.pearsonr(x, y)
# r = 0.9956,  p = 0.0000